/**
 * Regenerates lib/quotes.js from the 真乘心語 .docx.
 *
 * Usage (from source/):
 *   node tools/import-quotes.mjs "C:/path/to/真乘心語.docx"
 *
 * How the document is read:
 *   - A .docx is a zip; the text lives in word/document.xml.
 *   - Runs (<w:t>) must be joined per paragraph (<w:p>) first. Stripping all
 *     tags in one pass runs every line together.
 *   - One saying begins at each "*" marker, which is the document's own
 *     convention.
 *
 * What gets left out, and why:
 *   - Section headings ("- 反省:"), including one glued to the tail of the
 *     saying above it.
 *   - Anything outside 12-36 characters. Shorter is a fragment; longer is a
 *     paragraph, and the card has room for one thought rather than a page.
 *   - Lines the source itself left damaged (an unclosed bracket). These are
 *     reported rather than repaired: the words are the user's, and quietly
 *     rewriting them would be worse than leaving them out.
 *
 * Needs `unzip` on PATH (Git Bash ships it).
 */
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

const MIN = 12;
const MAX = 36;

const docx = process.argv[2];
if (!docx) {
  console.error('usage: node tools/import-quotes.mjs <path to .docx>');
  process.exit(1);
}

const work = mkdtempSync(join(tmpdir(), 'quotes-'));
try {
  execFileSync('unzip', ['-o', docx, 'word/document.xml', '-d', work], { stdio: 'pipe' });
  const xml = readFileSync(join(work, 'word', 'document.xml'), 'utf8');

  const paragraphs = [...xml.matchAll(/<w:p[ >][\s\S]*?<\/w:p>/g)].map((m) =>
    [...m[0].matchAll(/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>/g)]
      .map((t) => t[1])
      .join('')
      .replace(/<[^>]+>/g, '')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/\u00a0/g, ' ')
      .trim()
  );

  const segments = paragraphs
    .filter(Boolean)
    .join('\n')
    .split(/[*＊✱٭]/)
    .map((s) =>
      s
        .replace(/[{｛][^}｝]*[}｝]/g, '')
        .replace(/\s*[-–—]\s*[^-–—:：]{1,12}[:：]\s*$/g, '')
        .replace(/^\s*[-–—]\s*/, '')
        .replace(/\s+/g, ' ')
        .trim()
    )
    .filter(Boolean);

  const PAIRS = [
    ['(', ')'],
    ['（', '）'],
    ['「', '」'],
    ['『', '』'],
    ['{', '}'],
  ];
  const damaged = (s) =>
    PAIRS.some(
      ([o, c]) => [...s].filter((ch) => ch === o).length !== [...s].filter((ch) => ch === c).length
    ) || /[；;、，,]\s*$/.test(s);

  const seen = new Set();
  const kept = [];
  const skipped = { heading: 0, short: 0, long: 0, damaged: [], dupe: 0 };

  for (const s of segments) {
    if (/[:：]$/.test(s)) { skipped.heading += 1; continue; }
    if (s.length < MIN) { skipped.short += 1; continue; }
    if (s.length > MAX) { skipped.long += 1; continue; }
    if (damaged(s)) { skipped.damaged.push(s); continue; }
    if (seen.has(s)) { skipped.dupe += 1; continue; }
    seen.add(s);
    kept.push(s);
  }

  const out = `/**
 * 真乘心語 — the daily line.
 *
 * Generated by tools/import-quotes.mjs from the user's own 真乘心語 document,
 * one entry per "*" marker, kept only where the line fits a phone card
 * (${MIN}-${MAX} characters).
 *
 * These are the user's words, not the app's. Do not reword them, do not
 * "improve" the punctuation, and do not apply the tone rules in lib/coach.js
 * to them — those exist to police copy the app writes itself.
 *
 * To refresh, re-run the importer against the document rather than editing
 * here, so this file stays a faithful copy of the source.
 */

const QUOTES = [
${kept.map((q) => `  ${JSON.stringify(q)},`).join('\n')}
];

/**
 * One saying per day, stable for the whole day.
 *
 * Keyed on the date so it does not reshuffle every time the app is opened —
 * a line that changes on each visit reads as noise rather than as a thought
 * to sit with.
 */
export function quoteForDate(dateStr) {
  if (!QUOTES.length) return "";
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) hash = (hash * 31 + dateStr.charCodeAt(i)) % 1000003;
  return QUOTES[hash % QUOTES.length];
}

export { QUOTES };
`;

  writeFileSync('lib/quotes.js', out);

  console.log(`paragraphs read: ${paragraphs.filter(Boolean).length}`);
  console.log(`segments after splitting on "*": ${segments.length}`);
  console.log(`kept: ${kept.length}`);
  console.log(
    `skipped — headings ${skipped.heading}, too short ${skipped.short}, ` +
      `too long ${skipped.long}, damaged ${skipped.damaged.length}, duplicates ${skipped.dupe}`
  );
  if (skipped.damaged.length) {
    console.log('\nThese looked damaged in the source document and were left out:');
    skipped.damaged.forEach((s) => console.log(`  ${s}`));
  }
  console.log('\nwrote lib/quotes.js');
} finally {
  rmSync(work, { recursive: true, force: true });
}
